// Using i386 Architecture
FROM i386/debian:jessie

RUN apt-get update && \
    apt-get install -y flex bison cmake build-essential python debhelper devscripts

ADD . /doxyparse

WORKDIR /doxyparse

ENTRYPOINT ["linux32"]
CMD ["sh", "deploy.sh"]
