# Using AMD64 Architecture
FROM debian:jessie

RUN apt-get update -qq && \
    apt-get install -y flex \
                       bison \
                       git \
                       cmake \
                       build-essential \
                       python \
                       debhelper \
                       devscripts

ADD . /doxyparse

WORKDIR /doxyparse

CMD ["sh", "compile-pkg.sh"]
