# Using AMD64 Architecture
FROM debian:jessie

RUN apt-get update -qq && \
    apt-get install -y flex \
                       bison \
                       git \
                       cmake \
                       build-essential \
                       python \
                       debhelper \
                       devscripts

RUN git clone https://github.com/GCES2018-2/doxyparse.git /doxyparse

WORKDIR /doxyparse

RUN ["sh", "scripts/sh/compile-pkg.sh"]
