.TH DOXYPARSE "1" "DATE" "doxyparse VERSION" "User Commands"
.SH NAME
doxyparse \- generates a tag file and/or a search index for a set of HTML files
.SH SYNOPSIS
.B doxyparse
[\fIsource file\fR...]
.SH DESCRIPTION
Parses source code and dumps the dependencies between the code elements.
.SH OPTIONS
.TP
\fB\-v\fR
Verbose mode.
.SH SEE ALSO
doxygen(1), doxytag(1), doxywizard(1).
